# repository/schema_template_repository.py
import logging
from typing import List, Optional, Dict, Any
from data_class.entity.table.schema_template import SchemaTemplate
from db.impl.postgres.postgres_db_manager import PostgresDBManager

logger = logging.getLogger(__name__)

import os


POSTGRES_DB_SCHEMA = os.getenv("DB_SCHEMA")

class SchemaTemplateRepository:
    def __init__(self, db_manager: PostgresDBManager):
        self.db = db_manager
        self.table = POSTGRES_DB_SCHEMA + "." + "schema_template"

    def _prepare_params(self, entity: SchemaTemplate, include_id: bool = False) -> Dict[str, Any]:
        """
        Prepara i parametri per il DB.
        Psycopg 3 gestisce il campo 'schema' (dict) come JSONB nativo.
        Non includiamo il campo 'serial' negli insert/update perché è una column identity GENERATEd by DB.
        """
        params = {
            "name": entity.name,
            "schema": entity.schema if isinstance(entity.schema, dict) else {},
            "description": entity.description,
            "version": entity.version,
            "issued": entity.issued,
            "modified": entity.modified,
            # do NOT include 'serial' here for inserts/updates; DB will generate it
        }
        if include_id:
            params["id"] = entity.id
        return params

    def save(self, entity: SchemaTemplate) -> Optional[SchemaTemplate]:
        """Inserisce un nuovo template e ritorna l'entità completa di ID."""
        params = self._prepare_params(entity)
        cols = ", ".join(params.keys())
        placeholders = ", ".join([f"%({c})s" for c in params.keys()])
        
        query = f"INSERT INTO {self.table} ({cols}) VALUES ({placeholders}) RETURNING *"
        
        with self.db as db:
            row = db.execute_and_return(query, params)
            return SchemaTemplate(**row) if row else None

    def update(self, entity: SchemaTemplate) -> int:
        """Aggiorna un template esistente tramite ID."""
        if not entity.id:
            raise ValueError("ID mancante per l'aggiornamento dello schema template")
            
        params = self._prepare_params(entity, include_id=True)
        # exclude 'id' from set clauses and also do NOT update 'serial'
        set_clauses = ", ".join([f"{col} = %({col})s" for col in params.keys() if col != 'id'])
        
        query = f"UPDATE {self.table} SET {set_clauses} WHERE id = %(id)s"
        
        with self.db as db:
            return db.execute_command(query, params)

    def get_by_id(self, id: str) -> Optional[SchemaTemplate]:
        query = f"SELECT * FROM {self.table} WHERE id = %s"
        with self.db as db:
            row = db.execute_and_return(query, (id,))
            return SchemaTemplate(**row) if row else None

    def get_by_name(self, name: str) -> Optional[SchemaTemplate]:
        query = f"SELECT * FROM {self.table} WHERE name = %s"
        with self.db as db:
            row = db.execute_and_return(query, (name,))
            return SchemaTemplate(**row) if row else None

    def find_all(self, limit: Optional[int] = None, offset: Optional[int] = None) -> List[SchemaTemplate]:
        query = f"SELECT * FROM {self.table} ORDER BY name"
        if limit: query += f" LIMIT {limit}"
        if offset: query += f" OFFSET {offset}"
        
        with self.db as db:
            rows = db.query(query)
            return [SchemaTemplate(**row) for row in rows]

    def search_by_description(self, search_term: str) -> List[SchemaTemplate]:
        query = f"SELECT * FROM {self.table} WHERE description ILIKE %s"
        with self.db as db:
            rows = db.query(query, (f"%{search_term}%",))
            return [SchemaTemplate(**row) for row in rows]

    def delete(self, id: str) -> int:
        query = f"DELETE FROM {self.table} WHERE id = %s"
        with self.db as db:
            return db.execute_command(query, (id,))

    def count_all(self) -> int:
        query = f"SELECT COUNT(*) as count FROM {self.table}"
        with self.db as db:
            result = db.execute_and_return(query)
            return result["count"] if result else 0