from agents.states.mapping_schema_state import State
from typing import Dict, List, Literal, Union
from langgraph.types import Command

import json
from json_repair import repair_json
import traceback

from mappings.mapper import Mapper

class ValidationNode:
    """
    Node responsible for validating the mapping produced by an LLM.
    """

    def __init__(self):
        pass

    def _extract_json(self, json_text: str) -> Union[List[Dict], None]:
        """
        Repair and deserialize JSON generated by the LLM.
        """
        try:
            repaired_text = repair_json(json_text)
            parsed_json = json.loads(repaired_text)

            if isinstance(parsed_json, dict):
                return parsed_json

            print("Warning: LLM output is not in the expected mapping format.")
            return None

        except Exception as e:
            print(f"Failed to parse/repair JSON: {e}")
            return None

    def __call__(self, state: State) -> Command[Literal["llm_node", "writer_node"]]:
        """
        Validate the mapping against provided samples and schema.
        """
        print("Validating mapping with samples...")
        state.error_messages = []  # Reset previous error log

        print(f"Stato iniziale validation - feedback: {state.feedback}")
        
        # 🔥 DEBUG: Verifica cosa c'è nello state
        if state.mapping:
            print(f"Generated mapping: {state.mapping}")
        else:
            print("No mapping found in state!")

        # --------------------------------------------------------
        # Phase 1: Extract mapping JSON from LLM output
        # --------------------------------------------------------
        try:
            mapping_str = state.chat_history[-1].content  # Last message from LLM
            generated_mapping = self._extract_json(mapping_str)

            print("Generated mapping:", generated_mapping)

            if not generated_mapping:
                feedback_msg = (
                    "Output is not a valid JSON array for the mapping. "
                    "Please regenerate an array of mapping objects."
                )
                return Command(
                    goto="llm_node",
                    update={"valid": False, "feedback": feedback_msg, "mapping": None},
                )

        except Exception as e:
            feedback_msg = f"Error in processing LLM output: {str(e)}"
            print(traceback.format_exc())
            return Command(
                goto="llm_node",
                update={"valid": False, "feedback": feedback_msg, "mapping": None},
            )

        # --------------------------------------------------------
        # Phase 2: Validate mapping against target schema
        # --------------------------------------------------------
        try:
            target_schema = state.dst_schema
            src_schema = state.src_schema
        except AttributeError:
            print(traceback.format_exc())
            raise RuntimeError("dst_schema or src_schema is missing from the state.")

        valid = True
        self.mapper=Mapper(mapping_spec= generated_mapping,src_schema= src_schema, dst_schema= target_schema)

        for i, sample in enumerate(state.samples):
            transformed_sample, valid_mapping, errors = self.mapper.apply_mapping(sample)

            print(f"Sample {i+1} validation result: {valid_mapping}, Errors: {errors}, Transformed: {transformed_sample}")
            state.mapped_samples.append(transformed_sample)

            if not valid_mapping:
                valid = False
                state.error_messages.append(
                    f"Mapping validation failed for sample {i+1}:\nOutput: {transformed_sample}"
                )
                state.error_messages.extend(
                    [f"Sample {i+1}: {err}" for err in errors]
                )

        # --------------------------------------------------------
        # Phase 3: Return next command based on validation result
        # --------------------------------------------------------
        if valid:
            print("Mapping validated successfully!")
            return Command(
                goto="writer_node",
                update={
                    "mapping": generated_mapping,
                    "valid": True,
                    "mapped_samples": [
                        self.mapper.apply_mapping(sample)[0] for sample in state.samples
                    ],
                },
            )
        else:
            print("Invalid mapping. Validation errors:", state.error_messages)
            feedback_msg = "The mapping is invalid. Errors found:\n" + "\n".join(
                state.error_messages
            )
            # ✅ DEBUG: Log del feedback inviato
            print(f"Inviando feedback al llm_node: {feedback_msg}")
            return Command(
                goto="llm_node",
                update={
                    "valid": False,
                    "feedback": feedback_msg,
                    "mapping": generated_mapping,
                    "mapped_samples": [],
                },
            )